version: '2'
services:
    sentry-app:
        image: sentry
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sentry-mysql:3306/sentry?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sentry-mysql:
        extends:
            file: mysql.yml
            service: sentry-mysql
